// <auto-generated />
using ArticleViewCounter.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArticleViewCounter.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArticleViewCounter.Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfViews")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Article");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Murat Dinç",
                            Content = ".NET 8 ve C# Kasım 2023 sürümü, .NET dünyasında sadece bir sürüm yükseltmesi değil, aynı zamanda ASP.NET Core proje geliştirmenin geleceğini şekillendirecek yeniliklerle dolu bir dönüm noktasıdır. Yeni sürüm, performans iyileştirmelerinden kod yazma pratiklerine, verimliliği artıran özelliklerden geliştirici deneyimini zenginleştiren araçlara kadar bir dizi yenilik getiriyor.\r\n\r\nMakalede Primary Constructors, Collection Expressions, Default Lambda Parameters gibi dikkat çekici özelliklerin yanı sıra, daha özel alanlarda kullanılabilecek Inline Arrays ve deneysel çalışmalar için kullanabileceğimiz Experimental Attribute gibi ileri seviye konseptlere de değineceğiz. Ayrıca, C# 11'den itibaren kullanıma sunulan ancak .NET 8 ile daha geniş bir kitleye ulaşması beklenen Raw String Literals gibi özelliklerin pratik kullanımlarını inceleyeceğiz.",
                            NumberOfViews = 0,
                            Title = ".NET Core: C# 12 ve .NET 8'deki Bazı Yeni Özellikler"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Enes Can Yılmaz",
                            Content = "Merhabalar\r\n\r\nBugün sizinle .NET Core ile ilgili kaynakları paylaşmak istiyorum. .NET Core ile ilgili kendimi geliştirdiğim kaynakları sizinle de paylaşmak istedim!\r\n\r\nBu kaynaklar, .NET Core hakkında daha fazla bilgi edinmek, projelerinizde kullanmak veya becerilerinizi geliştirmek isteyenler için son derece yararlı olabilir.\r\n\r\nUmarım bu kaynaklar, .NET Core ile ilgili yolculuğunuzda size yardımcı olur.\r\n\r\nTeşekkürler ve iyi çalışmalar!",
                            NumberOfViews = 0,
                            Title = ".NET Core Öğrenme Kaynaklarım"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Ethem Boynukara",
                            Content = "Merhabalar,\r\n\r\nBu yazıda .NET ekosisteminin yeni framework’ü .NET Core’dan, birlikte gelen bazı yeniliklerden ve firmamızda projelerde kullanılan .NET Framework’ü ile yazılmış kütüphanenin .NET Core’a geçiş sürecininden bahsedeceğim.\r\n\r\nGöç hikayemize direk geçiş yapmak için tıklayabilirsiniz.\r\n\r\nİlk olarak .NET Framework, .NET Core, .NET Standard’ın ne olduğunu kısaca açıklayalım.",
                            NumberOfViews = 0,
                            Title = ".NET Framework’ten .NET Core‘a Göç Hikayemiz"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Kübra Balaban",
                            Content = "Her gün yeni bir gün ve bu yeni gün ile birlikte bir sürü yenilik ile karşılaşıyoruz, taaa ki gün batımına kadar. Her gün hayatımıza bir yenisini ekleyip keşfettiğimiz teknolojiler bu teknoljilerden biri de .Net Core.\r\n\r\nYazılım sektöründe olan hızlı dönüşüm ve yenilikler ile birlikte, web uygulaması geliştirmek için bir çok teknoloji bulunmaktadır Asp .Net Core bu teknolojilerin başında gelmektedir.",
                            NumberOfViews = 0,
                            Title = ".Net Core API Geliştirme"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Mehmed Emre AKDİN",
                            Content = "Öncelikle türkçesini “Arayazılım/Arakatman” olarak çevirebileceğimiz middleware kavramı sadece ASP.NET Core’a özgü bir kavram değildir. Genel olarak WEB mimarilerinde request(istek)’den, response(cevap)’a kadar gerçekleşen süreç middleware olarak adlandırılır. Eğer ASP.NET Core içinde bir tanımlama yapmamız gerekirse, uygulamamıza gelen HTTP request(istek) ve response(cevap) ‘ larını işlememize olanak sağlayan C# sınıflardır demek doğru olacaktır. Bunu bir nevi filtreleme işlemi olarak düşünebilirsiniz. Yani normal bir süreçte uygulamamıza gelen istekler, tanımlanan middleware ‘lerden geçerek uygulamamıza ulaşır, uygulamamızın cevabı oluşturulduktan sonra bu cevap yine tanımlanan middleware ’lerden geçerek kaynağa ulaşır ve süreç tamamlanır. Middleware‘ler dememden anlayacağınız üzere birden çok tanımlanabilirler ve çeşitli amaçlarla kullanılırlar. Aklımızda bazı şeylerin hafiften şekillenmeye başlaması için middleware‘lerin kullanılabileceği bazı alanlara örnekler vermek istiyorum:",
                            NumberOfViews = 0,
                            Title = "ASP.NET Core Middleware Nedir?"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Eren Yılmaz",
                            Content = "Herkese selamlar, bugün bir başka içerik ile karşınızdayım. 🙂\r\n\r\nBu yazımda, sizlere bir micro orm aracı olan “Dapper” ile ilgili bilgi vermeye çalışacağım.\r\n\r\nÖnceki yazılarımı takip edenler hatırlayacaktır, SOLID prensiplerine dikkat ederek geliştirmeye başladığım bir projeyi, Entity Framework orm aracını kullanarak veri tabanı üzerinde işlemler yapacak şekilde kodlamıştım. Bu içeriği merak edenler, buradan makaleye erişebilirler.\r\n\r\nDapper orm aracını projeye implemente edecek, ve bu işlemden sonra projemizi Entity Framework üzerinden Dapper’a geçireceğiz. Bu işlemi yaparken, SOLID prensiplerine uygun kodlama yapmanın bize ne kadar avantaj sağladığını deneyimlerek göreceğiz.",
                            NumberOfViews = 0,
                            Title = ".Net Core — Dapper İmplementasyonu"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Veysel Mutlu",
                            Content = "Serilog , .NET uygulamaları için en popüler Log kitaplıklarından(libraries) birisidir. Kurulumu kolaydır ve çok sayıda güçlü özellik sunar. Yazılım geliştiricilerin özelleştirilmiş kodlarını buna eklemelerine ve bu kitaplığın işlevselliğini daha da genişletmelerine olanak tanıyan birçok uzantı noktasına sahiptir. Bu makale sonunda, metin tabanlı Log dosyalarına nasıl mesaj kaydedebileceğinizi göstereceğim.\r\n\r\nSerilog nedir?\r\nYazılım uygulamalarının en can alıcı noktalarından biri işleyişteki her bir adımı raporlayıp kayıt altına alan log mekanizmalarıdır diyebiliriz. Serilog , uygulamanıza bazı harika tanılama özellikleri eklemek için kullanılabilecek .NET uygulamaları için yapısal bir log kitaplığıdır(library).\r\n\r\nYazılım geliştiricilerin dosyalara, consola, veri tabanlarına ve mesaj kuyruklarına dahil olmak üzere yüzlerce farklı hedefe mesajlarını kaydetmelerine olanak tanır.",
                            NumberOfViews = 0,
                            Title = "ASP.NET Core — Serilog İle Veri Loglama"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
